### ISSUE TITLE
Separate out config from application code

### ISSUE THREAD

**Issue by redfast00** [12urenloop/livesite#4]
Currently, this is a line in the source code of the application: https://github.com/12urenloop/livesite/blob/039b4afa6483afb5632185ce68dbe3829a5c7106/src/Leaderboard.svelte#L5-L6

This should be moved to a separate, git-ignored file. This will make deploying easier and will remove a pitfall:

- when you currently want to deploy a new version, you first have to stash the changed file with the config, then pull, then unstash again
- pitfall: if a sysadmin deploys the application as-is, it will run, but it will not work, without an obvious error. If a git-ignored file is used as config file, this file will be missing during deployment, leading to a more obvious error.

**Comment by NuttyShrimp** [comment]
Closed as of #6
